# THIS ANSIBLE PLAYBOOK FOR DEPLOYING AND INSTALLATION OF IRODS
# MAINTAINER Ahmed Abdullah <ahmedaabdulwahed@gmail.com>

- hosts: servers
  sudo: yes
  vars: 
    cloud: true
  roles:
   - role: common  

# Install PostgreSQL
- hosts: servers
  sudo: yes
  vars:
    cloud: true
  tasks:
   - include: roles/common/tasks/postgresql.yml

- hosts: masters
  sudo: yes
  sudo_user: postgres
  gather_facts: no
  vars:
    cloud: true
  tasks:
   - include: roles/common/tasks/db.yml

# Install iCAT

- hosts: masters
  sudo: yes
  vars:
    cloud: true
  roles:
   - role: icat

# install Resources
- hosts: slaves
  sudo: yes
  vars:
    cloud: true
  roles:
   - role: resources

# initialize iCAT & iRODS replica & iDROP2
- hosts: masters
  sudo: yes
  vars:
    cloud: true
  roles:
    - role: init
    - role: replica
    - role: idrob2
