---
- name: configure PostgreSQL
  template: src=postgresql.j2 dest=/etc/postgresql/9.4/main/postgresql.conf

- name: Restart PostgreSQL
  service: name=postgresql state=restarted

- name: Create PostgrSQL Database
  postgresql_db: name={{dbname}}

- name: grant access to user
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
